config/routes.rb
Hackday::Application.routes.draw do
  resources :hacks
  resources :votes

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/results' => 'votes#results', :as => :results
  root :to => 'votes#index'
end

app/models/hack.rb
class Hack
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :authors, :type => String
  field :url, :type => String

  validates_presence_of :name, :description, :authors
  
  has_many :votes
  
  def to_s
    name
  end
end

app/models/vote.rb
class Vote
  include Mongoid::Document
  field :email, :type => String

  belongs_to :hack
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hacks_controller.rb
class HacksController < InheritedResources::Base
  def update
    update!{ hacks_path }
  end

  def create
    create!{ hacks_path }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:email] = auth_hash[:info][:email]
    redirect_to '/'
  end

  protected

  def auth_hash
    request.env["omniauth.auth"]
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :login
  
  def index
    if Vote.where(:email => session[:email]).any?
      flash[:notice] = "You've already voted"
      redirect_to results_path
    else
      @hacks = Hack.all
      @vote = Vote.new
    end
  end
  
  def create
    if Vote.where(:email => session[:email]).any?
      flash[:notice] = "You've already voted"
      redirect_to results_path
      return false
    end
    
    @vote = Vote.new(params[:vote])
    @vote.email = session[:email]
    if @vote.save
      redirect_to results_path
    else
      redirect_to root_path
    end
  end
  
  def results
    @hacks = Hack.all
  end
  
  protected
  
  def login
    unless session[:email].present?
      redirect_to '/auth/google_apps'
      return false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true).render(text).html_safe
  end
end

app/views/hacks/_form.html.haml
= simple_form_for @hack, :html => { :class => 'form-horizontal' } do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :placeholder => "What's it called?"
    = f.input :description, :as => :text, :input_html => {:rows => 6}, :label => 'Description (markdown)'
    = f.input :authors, :placeholder => "Who built it? (full names please)"
    = f.input :url, :placeholder => "Optional but awesome"

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to 'Cancel', hacks_path, :class => 'btn'

app/views/hacks/edit.html.haml
.page-header
  %h1 Edit Hack Details

= render 'form'

app/views/hacks/index.html.haml
.page-header
  %h1 Hacks

- @hacks.each do |hack|
  .hack.well
    %h2
      = hack.name
      %small
        by
        = hack.authors
    = markdown hack.description
    = link_to('View', hack.url) if hack.url.present?

app/views/hacks/new.html.haml
.page-header
  %h1 Submit Hack

= render 'form'

app/views/hacks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @hack.name
%p
  %b Description:
  = @hack.description
%p
  %b Authors:
  = @hack.authors
%p
  %b Url:
  = @hack.url

= link_to 'Edit', edit_hack_path(@hack)
\|
= link_to 'Back', hacks_path

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : "Hackday"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    = stylesheet_link_tag "application", :media => "all"


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"}Hackday

    .container-fluid

      .row-fluid
        .span3
          .well
            %h3 What's a Hack?
            %p The Forward Developers have made software projects in just a single day.
            %p Vote for your favourite project and the team with the most votes win an iPad.
            %p Winners will be announced on Monday afternoon
            
        .span9
          = yield
    
      %footer
        %p &copy; Forward 2012
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/votes/index.html.haml
.page-header
  %h1 Vote For your favourite hack

= form_for @vote do |form|
  - @hacks.sort_by{ rand }.each do |hack|
    .row
      .hack.well.span9
        .row
          .span1= form.radio_button :hack_id, hack.id
          .span4
            %h2
              = hack.name
              %small
                by
                = hack.authors
            = markdown hack.description
            = link_to('View demo', hack.url, :class => 'btn btn-info', :style => 'color:#fff;') if hack.url.present?
  = form.submit 'Place Vote', :class => 'btn-primary btn-large'

app/views/votes/results.html.haml
%ul
  - @hacks.sort_by{|h| h.votes.count}.reverse.each do |hack|
    %li
      %h2
        = hack.name
        %small
          = pluralize hack.votes.count, 'vote'